import React, { useEffect, useState} from "react"
import "./meista.css"
export default function About() {

    const [shouldAnimate, setShouldAnimate] = useState(false);

    useEffect(() => {
    const handleScroll = () => {
        const scrollPosition = window.pageYOffset;
        // Tämä kertoo, missä kohtaa animaation kuuluu lähteä liikkelle, tai mitä ikinä halutaankaan tehdä
        const targetPosition = 500;
        if (scrollPosition > targetPosition) {
        setShouldAnimate(true);
        }
    };

    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
    }, []);

    return (
        <div>
        <h2 className="alaotsikko">Tällä sivulla tulee skrollamalla esiin uusi teksti</h2>
        <p className="teksti">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dictum laoreet lacus vehicula aliquam. Suspendisse porttitor nisi nec metus lobortis accumsan. Integer sed quam sit amet orci pellentesque gravida. Curabitur eu molestie diam. Nam blandit sodales aliquet. Nullam metus erat, pharetra sed urna iaculis, mattis lobortis leo. Etiam eu dapibus.
        Duis venenatis luctus pretium. Morbi tincidunt purus in diam eleifend posuere. In commodo est non eros condimentum, a vestibulum enim tempor. Etiam dignissim nulla et ornare aliquet. Curabitur non quam justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris tincidunt eu lectus sed sodales. Cras dignissim ac dolor id luctus. Nullam finibus interdum mauris et ultrices. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec accumsan tortor eget nulla mattis, non maximus dui ornare. Sed tristique mi vitae ligula rhoncus lacinia. Aenean tempor turpis purus, et aliquam erat euismod non. Sed sed turpis sit amet elit mollis fringilla.

        Aliquam porttitor mauris eget vestibulum luctus. Morbi hendrerit mollis erat vitae placerat. In fermentum est vel purus suscipit blandit. Vestibulum ut tempor dui. In et lorem lectus. Integer eu imperdiet odio. Sed facilisis libero sem, laoreet iaculis metus pellentesque sit amet. Suspendisse et nibh a lectus feugiat ullamcorper. Suspendisse odio sem, laoreet in iaculis consequat, sagittis ut enim. Morbi efficitur iaculis nibh, eget scelerisque eros interdum nec. Pellentesque tincidunt vulputate odio. Sed volutpat, leo at pulvinar auctor, ipsum arcu euismod orci, in suscipit justo diam nec ante. In elementum accumsan augue non efficitur. In tincidunt leo vitae lobortis varius. Nulla felis quam, vehicula vel molestie in, ornare sed nunc.

        In pretium tincidunt risus quis suscipit. Vivamus a leo sed mi porttitor lacinia at in magna. Proin semper fermentum justo ac tincidunt. Nam bibendum blandit porttitor. Etiam convallis lectus arcu, gravida ornare lectus ornare sed. Quisque non nunc facilisis, ultricies ante nec, vehicula augue. Curabitur suscipit mi vitae est sodales viverra.

        Curabitur in venenatis odio. Mauris commodo eros ac libero commodo ullamcorper. Quisque blandit turpis sit amet arcu sollicitudin maximus. Cras ullamcorper urna eget risus auctor bibendum. Ut imperdiet felis ipsum, vitae aliquam libero imperdiet at. Maecenas fermentum mi eu bibendum imperdiet. Sed libero nisi, porta condimentum magna id, dictum dictum orci. Sed a tellus in diam convallis sodales non eu quam. Nullam ultricies massa hendrerit ligula maximus, feugiat posuere urna faucibus. Mauris sed tellus massa. Cras eget lectus porttitor, tincidunt justo eget, feugiat lorem.

        Pellentesque varius nisi magna, eu pharetra justo fringilla nec. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dapibus vestibulum mi ac pharetra. Vivamus dapibus elementum est quis eleifend. Sed condimentum, arcu eu eleifend euismod, justo velit porttitor neque, et lacinia justo turpis vitae lorem. Nunc lacinia lorem a lacus laoreet dapibus. Curabitur blandit mollis elit sit amet rhoncus. Nam vitae massa at risus consectetur fermentum eget nec ipsum. Suspendisse tincidunt ac enim vel posuere. Etiam id dui vel augue tincidunt tempus. Phasellus scelerisque dapibus eros blandit pulvinar. Nam finibus ante eu efficitur eleifend. Donec vehicula augue odio, at rhoncus odio eleifend vel.

        Sed eu volutpat sem, ac vehicula elit. Sed vitae fermentum urna. In magna libero, ultrices efficitur cursus a, dapibus eu nulla. Donec et eros sit amet nisl hendrerit malesuada vitae eget orci. Aliquam et felis fermentum, scelerisque metus eget, auctor nulla. In lorem arcu, condimentum et lacus eget, viverra consectetur massa. Donec vitae risus tincidunt, tristique lorem facilisis, vehicula odio. Aenean tincidunt nunc non orci dictum molestie. Ut sit amet nisi quis justo eleifend dignissim. Sed cursus, velit ut suscipit dictum, diam odio sagittis sapien, in posuere magna mi eu justo. Mauris sit amet ex vitae nunc porttitor varius.

        Donec consectetur euismod turpis. Nullam sed iaculis eros. Vestibulum sapien leo, ornare quis purus eget, fringilla blandit mi. Duis vel nisl nisl. Ut at quam ac ligula blandit blandit. Integer nec ex eget turpis tempor facilisis. Quisque felis nisl, aliquet sed tortor ut, tempus aliquet sem. Nulla id ullamcorper tortor, ut ultricies augue. Aenean tristique maximus turpis sit amet fringilla. Donec consectetur tempor purus vitae blandit. Vestibulum diam urna, tristique sed justo id, finibus fermentum tellus. Ut elit elit, mattis ut justo quis, hendrerit semper massa. Phasellus facilisis tortor felis, a bibendum elit tristique at. In quis consequat orci. Pellentesque gravida molestie sapien vitae semper. In hac habitasse platea dictumst.

        Maecenas ullamcorper volutpat nibh nec faucibus. Maecenas sed dui eleifend, scelerisque ante eu, faucibus velit. Etiam sit amet faucibus dolor, ac fermentum velit. Sed consectetur tempor eros vel dapibus. Proin semper erat ac velit dignissim dapibus. Aliquam erat volutpat. Vivamus tristique luctus tellus, sit amet fringilla libero. In scelerisque suscipit elit non pellentesque. Praesent nulla est, lacinia non sagittis at, placerat in mi. Ut cursus ut tellus sed tincidunt. Donec sollicitudin lorem mi. Vivamus pharetra euismod dolor sit amet sodales. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam tempor rhoncus interdum. Vestibulum neque mi, varius quis fermentum vel, accumsan eu velit. Quisque dolor velit, dapibus eu nunc sit amet, iaculis varius ex.

        Donec ultrices sollicitudin dui in porta. Donec in consectetur libero. Quisque et felis ultrices mauris tristique rutrum non sit amet lacus. Sed molestie lectus magna, et efficitur lorem rhoncus sit amet. Maecenas convallis lorem ut sapien dignissim mollis. Ut bibendum volutpat neque, eget rhoncus nisl mattis sit amet. Praesent malesuada sapien vel commodo ornare. In hac habitasse platea dictumst.

        Etiam luctus dapibus lectus id ornare. Etiam nec feugiat nisi. Cras vulputate pulvinar justo, in mattis mi blandit eu. Curabitur suscipit, leo sit amet pulvinar euismod, quam libero consectetur nibh, sed bibendum eros lorem nec erat. Phasellus pulvinar nibh et metus ultricies hendrerit. Pellentesque tincidunt aliquam gravida. Suspendisse sed ex tempor, ornare lacus eu, aliquam elit. Suspendisse purus nisi, sollicitudin id sapien a, dapibus imperdiet turpis.

        Nunc vel ipsum lorem. Nunc auctor diam ac nibh imperdiet venenatis. In ultricies congue purus eget varius. Donec blandit, leo eu pharetra convallis, arcu ex viverra tortor, in blandit purus eros ut ipsum. Ut et diam nec nunc placerat luctus. Cras mattis dui placerat elit consequat, sed hendrerit massa pharetra. Morbi gravida, lorem id mollis molestie, est quam aliquet arcu, ut vulputate elit justo in tortor. Ut a nisi vitae sem sodales posuere id in sem. Donec eu augue eros. Praesent posuere suscipit malesuada. Sed congue diam nibh, eget viverra lectus placerat quis. Nunc id lectus tincidunt, ullamcorper urna vitae, pretium nisl.

        Nam vitae varius velit, nec vehicula lacus. Phasellus pharetra velit in neque commodo, sit amet molestie turpis suscipit. Nulla ut felis ac eros faucibus tincidunt eget at sapien. Nulla facilisi. Phasellus sodales, lacus id tincidunt vehicula, ex ante euismod leo, in porta enim ex at orci. Praesent vitae molestie lorem. Proin dapibus elit sit amet euismod feugiat. Maecenas felis odio, commodo et consequat eu, pretium at urna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras vel ligula lectus. Nulla elementum purus ut neque luctus venenatis.
        </p>
        <h2 className={shouldAnimate.toString()}>Tämä ilmestyy scrollatessa ja tämän voisi animoida kauniisti. Näitä voi myös tehdä paljon lisää</h2>
        <p>
        Duis venenatis luctus pretium. Morbi tincidunt purus in diam eleifend posuere. In commodo est non eros condimentum, a vestibulum enim tempor. Etiam dignissim nulla et ornare aliquet. Curabitur non quam justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris tincidunt eu lectus sed sodales. Cras dignissim ac dolor id luctus. Nullam finibus interdum mauris et ultrices. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec accumsan tortor eget nulla mattis, non maximus dui ornare. Sed tristique mi vitae ligula rhoncus lacinia. Aenean tempor turpis purus, et aliquam erat euismod non. Sed sed turpis sit amet elit mollis fringilla.

        Aliquam porttitor mauris eget vestibulum luctus. Morbi hendrerit mollis erat vitae placerat. In fermentum est vel purus suscipit blandit. Vestibulum ut tempor dui. In et lorem lectus. Integer eu imperdiet odio. Sed facilisis libero sem, laoreet iaculis metus pellentesque sit amet. Suspendisse et nibh a lectus feugiat ullamcorper. Suspendisse odio sem, laoreet in iaculis consequat, sagittis ut enim. Morbi efficitur iaculis nibh, eget scelerisque eros interdum nec. Pellentesque tincidunt vulputate odio. Sed volutpat, leo at pulvinar auctor, ipsum arcu euismod orci, in suscipit justo diam nec ante. In elementum accumsan augue non efficitur. In tincidunt leo vitae lobortis varius. Nulla felis quam, vehicula vel molestie in, ornare sed nunc.

        In pretium tincidunt risus quis suscipit. Vivamus a leo sed mi porttitor lacinia at in magna. Proin semper fermentum justo ac tincidunt. Nam bibendum blandit porttitor. Etiam convallis lectus arcu, gravida ornare lectus ornare sed. Quisque non nunc facilisis, ultricies ante nec, vehicula augue. Curabitur suscipit mi vitae est sodales viverra.

        Curabitur in venenatis odio. Mauris commodo eros ac libero commodo ullamcorper. Quisque blandit turpis sit amet arcu sollicitudin maximus. Cras ullamcorper urna eget risus auctor bibendum. Ut imperdiet felis ipsum, vitae aliquam libero imperdiet at. Maecenas fermentum mi eu bibendum imperdiet. Sed libero nisi, porta condimentum magna id, dictum dictum orci. Sed a tellus in diam convallis sodales non eu quam. Nullam ultricies massa hendrerit ligula maximus, feugiat posuere urna faucibus. Mauris sed tellus massa. Cras eget lectus porttitor, tincidunt justo eget, feugiat lorem.

        lerisque ullamcorper felis, finibus viverra ligula egestas ac. Donec pulvinar semper varius. Fusce nec consequat est. Sed non felis non ex sodales molestie id id dolor. Fusce facilisis fermentum velit efficitur ultricies. Proin sit amet consectetur risus. Curabitur vehicula quis mi id aliquam. Vivamus laoreet sagittis dignissim. Aliquam dapibus eros non justo molestie ullamcorper. Donec vitae leo viverra, cursus elit nec, semper sem. Sed elementum ex dui, dapibus cursus lorem dapibus nec.

        Donec aliquet lobortis mi eget finibus. Donec at ex eget ex interdum ullamcorper. Pellentesque suscipit eget urna eu semper. Donec fermentum lectus eget metus porta egestas. Nam vitae lacus erat. Aliquam erat volutpat. Vivamus porttitor nunc quis dui tincidunt faucibus. Duis at ornare metus, vitae varius nisi. Quisque congue rutrum enim, quis convallis est imperdiet a.

        Mauris congue dignissim quam, et porta sapien dapibus id. Pellentesque vestibulum non dui sed iaculis. Praesent fringilla ipsum elementum, tincidunt augue at, viverra ante. Aliquam dignissim vulputate elit vel lacinia. Integer dignissim elit vitae arcu tincidunt semper. Etiam fringilla posuere dapibus. Morbi maximus eu turpis non mollis. Cras molestie leo vulputate varius accumsan. Aenean vestibulum ut nunc quis tempus. Mauris ut aliquet risus. Vivamus dictum lobortis erat in ultricies. Curabitur eu sapien vel urna egestas efficitur.

        Nam at velit ut ante dapibus tempus. Cras ac mattis nisl, non maximus dui. Nullam efficitur dui rutrum felis suscipit efficitur. Donec sagittis pulvinar turpis, quis pretium enim rhoncus vitae. Aliquam eros ante, euismod at pharetra ac, lacinia ultrices augue. Nulla facilisi. Nullam a ipsum vel ligula ornare feugiat. Integer sodales diam id ultrices rhoncus. Nullam quis elementum nisl. Integer scelerisque commodo dui, quis euismod tellus molestie at.

        Ut condimentum blandit nisi ut dignissim. Vestibulum viverra, ligula vel malesuada convallis, nisl nunc blandit ex, et consectetur lectus tellus in enim. Quisque pulvinar, turpis sed vulputate pharetra, mi lacus elementum leo, a posuere dui sapien at nisi. Phasellus finibus semper dictum. Proin et pellentesque lectus, eget venenatis felis. Ut mattis tellus nisl, a aliquam mauris egestas ut. Pellentesque maximus nulla et tortor consectetur lacinia. Donec non ligula ex. Nam cursus in ligula blandit mollis. In euismod, augue quis efficitur sollicitudin, felis diam varius mi, sed euismod felis ante sit amet tellus. Quisque vitae mattis ligula.

        Nam placerat tortor a dolor facilisis scelerisque. Praesent porttitor ex diam, in pretium risus efficitur vel. Vestibulum ligula leo, dapibus vel suscipit id, ornare sed tellus. Nulla facilisi. Vestibulum tempor gravida vehicula. Sed eget massa eu odio semper pellentesque. Quisque consequat enim in hendrerit elementum. Morbi massa turpis, fermentum nec purus ac, vulputate fermentum urna. Sed consectetur purus lacus, nec accumsan mi condimentum nec.

        Integer blandit, turpis eget porttitor finibus, dolor sem aliquam nisl, a sollicitudin purus ante quis tellus. Integer placerat nibh tortor, facilisis porta velit condimentum id. Proin eleifend mauris nec lectus luctus, laoreet eleifend quam varius. Morbi nec magna id magna auctor aliquam. Vestibulum tincidunt nisl nunc, eu elementum erat imperdiet quis. Donec ut justo vehicula justo sagittis sagittis. Sed eget pellentesque massa.

        Nullam scelerisque metus eget ornare vestibulum. Vestibulum condimentum ante a ipsum congue, id malesuada nisl semper. Aliquam sed feugiat nulla, id gravida augue. Integer efficitur malesuada quam id rhoncus. Duis vestibulum quam vitae viverra egestas. Nulla odio tortor, imperdiet dictum augue in, mollis molestie erat. Integer pulvinar tellus tortor, ut iaculis mi pulvinar id. Nunc vehicula rutrum odio, vel sagittis nisl egestas id. Curabitur hendrerit convallis placerat. Sed a tellus ultricies, tempus purus sit amet, egestas diam. Aenean eu cursus lacus, ac ultricies nunc. Nam dictum sodales placerat.

        Vestibulum tempor tortor tortor. Cras accumsan mauris quis massa ullamcorper, et maximus orci auctor. Morbi mauris nisl, iaculis at euismod et, blandit id magna. Sed fringilla sollicitudin tellus a volutpat. Aliquam ornare neque iaculis commodo rutrum. Integer sed tellus sapien. Vivamus dapibus hendrerit tortor, a dapibus odio hendrerit ut.

        Maecenas euismod tortor in porta consequat. Praesent a massa eget quam tempus feugiat. Nullam consequat lacus a purus faucibus egestas. Nunc sagittis mauris nisi, sed venenatis augue hendrerit id. Cras non mollis odio. Pellentesque leo erat, ultrices id urna non, imperdiet suscipit orci. Phasellus consequat augue quam, ut commodo nulla luctus vitae.

        Vivamus elit mauris, aliquet vel pulvinar sed, suscipit nec augue. Integer et sem consectetur, vulputate turpis ac, ornare nunc. Phasellus ut sollicitudin purus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse feugiat arcu eget mauris feugiat viverra. Ut gravida augue eget augue ullamcorper pretium. Curabitur non enim est. Sed consectetur, sapien sed egestas aliquam, erat ipsum mattis dolor, in rhoncus leo massa sit amet erat. Curabitur auctor tellus luctus, finibus ante eu, tincidunt arcu. Sed malesuada ornare odio in elementum. Integer eu lorem eleifend, faucibus ex non, ullamcorper eros. Pellentesque feugiat elit eget turpis pellentesque, sed commodo ipsum tincidunt. Pellentesque vulputate tempor enim, nec faucibus enim lobortis interdum.

        Vestibulum facilisis justo id erat vehicula, ac aliquet diam venenatis. In lobortis at felis pulvinar vulputate. Vivamus eu libero vitae lorem ultrices efficitur. Maecenas varius velit non ligula tristique, quis varius elit accumsan. Fusce id purus laoreet, rhoncus nisl quis, eleifend odio. Proin tempus ac nibh nec tristique. Duis erat nisi, fringilla quis vehicula sed, mollis ac risus. Ut orci nibh, tempor eu nulla id, commodo ullamcorper nisi.

        Nullam imperdiet justo vitae eros vestibulum, id porta elit ultricies. Suspendisse commodo vulputate purus ac posuere. Quisque at fringilla lorem. Vestibulum iaculis nisi sit amet egestas bibendum. Aliquam erat volutpat. Nullam a commodo nulla. Etiam ultricies ex mauris, et pellentesque massa cursus at. Vestibulum congue quis tellus sit amet consectetur. Etiam et magna ut elit lacinia viverra quis consectetur tortor. Cras vel augue et risus venenatis scelerisque. Nullam vulputate ante dolor, a iaculis justo tristique vitae. Sed sit amet mauris lectus. Morbi accumsan maximus erat a laoreet. Maecenas at neque sit amet eros malesuada suscipit quis id leo. Pellentesque urna mi, mollis eu tempus et, vulputate vitae justo. Pellentesque enim nibh, feugiat sit amet est eu, placerat facilisis ex.

        Nunc rutrum posuere vestibulum. Proin ultrices et ante non ornare. Fusce blandit sit amet eros nec sagittis. Curabitur sagittis ex et faucibus suscipit. Donec sit amet libero lacus. Nunc dapibus vel ipsum efficitur.
        </p>
        </div>
    )
};